# Generated by Django 4.1.5 on 2023-01-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_datetime',
            field=models.DateTimeField(null=True, verbose_name='created date'),
        ),
    ]
