# Generated by Django 4.1.5 on 2023-01-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_post_created_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Discussion',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='meeting',
            new_name='discussion',
        ),
    ]
